# Generated by Django 5.0.14 on 2026-10-04 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_batiment_geometrie_alter_borne_geometrie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inspection', models.DateField()),
                ('etat', models.CharField(choices=[('BON', 'Bon état'), ('A_SURVEILLER', 'À surveiller'), ('REPARATION_REQUISE', 'Réparation requise'), ('HORS_SERVICE', 'Hors service')], max_length=24)),
                ('pression_observee', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='assets.borne')),
                ('inspecteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_inspection', '-date_creation'],
            },
        ),
    ]
