# Generated by Django 5.0.14 on 2026-08-13 01:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_source', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('usage', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('superficie', models.FloatField()),
                ('date_creation_source', models.DateField(blank=True, null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_source', models.CharField(db_index=True, max_length=50)),
                ('municipalite', models.CharField(max_length=20)),
                ('date_entretien', models.DateField(blank=True, null=True)),
                ('pression_dynamique', models.PositiveIntegerField(blank=True, null=True)),
                ('date_mise_a_jour_source', models.DateField()),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentRue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_source', models.CharField(db_index=True, max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('type_rue', models.CharField(max_length=100)),
                ('type_camionnage', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_vitesse', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('autobus_autorise', models.BooleanField(default=False)),
                ('stationnement_hiver_interdit', models.BooleanField(default=False)),
                ('date_mise_a_jour_source', models.DateField()),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
