# Generated by Django 5.0.14 on 2026-08-13 21:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='borne',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='segmentrue',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326),
        ),
    ]
