# Generated by Django 5.0.14 on 2026-10-04 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_batiment_geometrie_alter_borne_geometrie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTRETIEN', 'Entretien'), ('REPARATION', 'Réparation'), ('REMPLACEMENT', 'Remplacement'), ('URGENCE', 'Urgence')], max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=12)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=12)),
                ('description', models.TextField()),
                ('planifiee_le', models.DateTimeField(blank=True, null=True)),
                ('terminee_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='assets.borne')),
                ('creee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
